//! The MJCF writer (docs/02-data-model.md §Format mapping, ADR-0004,
//! ADR-0008): nested `<body>`s in the resolved order, one `<joint>` per
//! movable edge inside the child body, `<inertial pos mass fullinertia>`
//! so MuJoCo does the principal-axes decomposition itself, meshes by stem
//! under `meshdir="meshes"`.

use riggen_core::glam::DVec3;
use riggen_core::{JointKind, Pose, Primitive};

use crate::resolve::{ExportOptions, ResolvedGeom, ResolvedJoint, ResolvedRobot};
use crate::xml::{Xml, num, quat, vec3};

/// The translucent orange of the unirobot example's collision class.
pub const COLLISION_RGBA: &str = "0.9 0.4 0.1 0.25";

pub fn write(robot: &ResolvedRobot, _options: &ExportOptions) -> String {
    let mut x = Xml::new();
    x.open("mujoco", &[("model", robot.name.clone())]);
    x.comment("Generated by riggen. Meshes are in meters (ADR-0008).");
    x.empty(
        "compiler",
        &[
            ("angle", "radian".into()),
            ("meshdir", "meshes".into()),
            ("autolimits", "true".into()),
        ],
    );

    x.open("default", &[]);
    x.open("default", &[("class", "visual".into())]);
    x.empty(
        "geom",
        &[
            ("type", "mesh".into()),
            ("contype", "0".into()),
            ("conaffinity", "0".into()),
            ("group", "2".into()),
        ],
    );
    x.close("default");
    x.open("default", &[("class", "collision".into())]);
    x.empty(
        "geom",
        &[("group", "3".into()), ("rgba", COLLISION_RGBA.into())],
    );
    x.close("default");
    x.close("default");

    if !robot.meshes.is_empty() {
        x.open("asset", &[]);
        for name in robot.meshes.keys() {
            x.empty(
                "mesh",
                &[("name", name.clone()), ("file", format!("{name}.stl"))],
            );
        }
        x.close("asset");
    }

    x.open("worldbody", &[]);
    if !robot.links.is_empty() {
        write_body(&mut x, robot, 0);
    }
    x.close("worldbody");
    x.close("mujoco");
    x.finish()
}

fn write_body(x: &mut Xml, robot: &ResolvedRobot, index: usize) {
    let link = &robot.links[index];
    let joint = robot.parent_joint(index);
    let mut attrs = vec![("name", link.name.clone())];
    if let Some(j) = joint {
        attrs.extend(pose_attrs(&j.origin));
    }
    x.open("body", &attrs);

    if index == 0 && robot.floating_base {
        x.empty("freejoint", &[("name", "root".into())]);
    }
    if let Some(j) = joint.filter(|j| j.kind.is_movable()) {
        write_joint(x, j);
    }
    if let Some(i) = &link.inertial {
        let m = &i.inertia;
        x.empty(
            "inertial",
            &[
                ("pos", vec3(i.com)),
                ("mass", num(i.mass)),
                (
                    "fullinertia",
                    // MuJoCo's order: Ixx Iyy Izz Ixy Ixz Iyz.
                    format!(
                        "{} {} {} {} {} {}",
                        num(m.x_axis.x),
                        num(m.y_axis.y),
                        num(m.z_axis.z),
                        num(m.y_axis.x),
                        num(m.z_axis.x),
                        num(m.z_axis.y)
                    ),
                ),
            ],
        );
    }
    for geom in &link.visuals {
        write_geom(x, "visual", geom);
    }
    for geom in &link.collisions {
        write_geom(x, "collision", geom);
    }
    for child in robot.child_joints(index) {
        write_body(x, robot, child.child);
    }
    x.close("body");
}

fn write_joint(x: &mut Xml, j: &ResolvedJoint) {
    let mut attrs = vec![
        ("name", j.name.clone()),
        (
            "type",
            match j.kind {
                JointKind::Prismatic => "slide",
                _ => "hinge",
            }
            .into(),
        ),
        ("axis", vec3(j.axis)),
    ];
    if let Some(l) = &j.limits {
        attrs.push(("range", format!("{} {}", num(l.lower), num(l.upper))));
    }
    let d = &j.dynamics;
    if d.damping != 0.0 {
        attrs.push(("damping", num(d.damping)));
    }
    if d.friction != 0.0 {
        attrs.push(("frictionloss", num(d.friction)));
    }
    if d.armature != 0.0 {
        attrs.push(("armature", num(d.armature)));
    }
    x.empty("joint", &attrs);
    if let Some(l) = &j.limits {
        // ADR-0004 §4: what MJCF cannot hold without an actuator is named,
        // not dropped.
        x.comment(&format!(
            "joint {}: effort {} velocity {} need an <actuator>; not written",
            j.name,
            num(l.effort),
            num(l.velocity)
        ));
    }
}

fn write_geom(x: &mut Xml, class: &str, geom: &ResolvedGeom) {
    let mut attrs = vec![("class", class.to_owned())];
    match geom {
        ResolvedGeom::Mesh { name, pose, .. } => {
            if class == "collision" {
                attrs.push(("type", "mesh".into()));
            }
            attrs.push(("mesh", name.clone()));
            attrs.extend(pose_attrs(pose));
        }
        ResolvedGeom::Primitive(p) => {
            // MJCF `size` is half-extents for a box and (radius, half-length)
            // for a cylinder / capsule — the classic mistake, pinned in
            // `primitive_sizes_are_half_extents`.
            let (kind, size, pose) = match p {
                Primitive::Box { pose, size } => ("box", vec3(*size * 0.5), pose),
                Primitive::Cylinder {
                    pose,
                    radius,
                    length,
                } => (
                    "cylinder",
                    format!("{} {}", num(*radius), num(length * 0.5)),
                    pose,
                ),
                Primitive::Sphere { pose, radius } => ("sphere", num(*radius), pose),
                Primitive::Capsule {
                    pose,
                    radius,
                    length,
                } => (
                    "capsule",
                    format!("{} {}", num(*radius), num(length * 0.5)),
                    pose,
                ),
            };
            attrs.push(("type", kind.into()));
            attrs.push(("size", size));
            attrs.extend(pose_attrs(pose));
        }
    }
    x.empty("geom", &attrs);
}

/// `pos` and `quat`, each only when it is not the default.
fn pose_attrs(pose: &Pose) -> Vec<(&'static str, String)> {
    let mut attrs = Vec::new();
    if pose.t != DVec3::ZERO {
        attrs.push(("pos", vec3(pose.t)));
    }
    if quat(pose.r) != "1 0 0 0" {
        attrs.push(("quat", quat(pose.r)));
    }
    attrs
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::test_util::every_joint_kind;

    const GOLDEN: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<mujoco model="test">
  <!-- Generated by riggen. Meshes are in meters (ADR-0008). -->
  <compiler angle="radian" meshdir="meshes" autolimits="true"/>
  <default>
    <default class="visual">
      <geom type="mesh" contype="0" conaffinity="0" group="2"/>
    </default>
    <default class="collision">
      <geom group="3" rgba="0.9 0.4 0.1 0.25"/>
    </default>
  </default>
  <asset>
    <mesh name="cube" file="cube.stl"/>
  </asset>
  <worldbody>
    <body name="base_link">
      <inertial pos="0 0 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
      <geom class="visual" mesh="cube"/>
      <geom class="collision" type="mesh" mesh="cube"/>
      <body name="upper" pos="0 0 0.1">
        <joint name="upper_joint" type="hinge" axis="0 1 0" range="-1 1" damping="0.1"/>
        <!-- joint upper_joint: effort 1 velocity 1 need an <actuator>; not written -->
        <inertial pos="0 0 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
        <geom class="visual" mesh="cube"/>
        <geom class="collision" type="mesh" mesh="cube"/>
        <body name="slider" pos="0 0 0.1">
          <joint name="slider_joint" type="slide" axis="0 0 1" range="-1 1"/>
          <!-- joint slider_joint: effort 1 velocity 1 need an <actuator>; not written -->
          <inertial pos="0 0 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
          <geom class="visual" mesh="cube"/>
          <geom class="collision" type="box" size="0.05 0.1 0.15" pos="0 0 0.01"/>
          <body name="wheel" pos="0 0 0.1">
            <joint name="wheel_joint" type="hinge" axis="0 0 1"/>
            <inertial pos="0 0.02 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
            <geom class="visual" mesh="cube" pos="0 0.02 0" quat="0.707106781187 0.707106781187 0 0"/>
            <geom class="collision" type="mesh" mesh="cube" pos="0 0.02 0" quat="0.707106781187 0.707106781187 0 0"/>
            <body name="tip" pos="0 0 0.1">
            </body>
          </body>
        </body>
      </body>
    </body>
  </worldbody>
</mujoco>
"#;

    #[test]
    fn golden_mjcf_for_every_joint_kind() {
        let b = every_joint_kind();
        let resolved = b.resolve().unwrap();
        let xml = write(&resolved, &ExportOptions::default());
        if xml != GOLDEN {
            for (i, (a, e)) in xml.lines().zip(GOLDEN.lines()).enumerate() {
                assert_eq!(a, e, "line {}", i + 1);
            }
            assert_eq!(xml.lines().count(), GOLDEN.lines().count());
        }
    }

    #[test]
    fn floating_base_adds_a_freejoint_under_the_root() {
        let b = every_joint_kind();
        let options = ExportOptions {
            floating_base: true,
            ..Default::default()
        };
        let resolved = crate::resolve(&b.robot, &b.store, &crate::ComputeNow, &options).unwrap();
        let xml = write(&resolved, &options);
        assert!(
            xml.contains("    <body name=\"base_link\">\n      <freejoint name=\"root\"/>\n"),
            "{xml}"
        );
    }

    #[test]
    fn primitive_sizes_are_half_extents() {
        // The classic mistake: MJCF `size` is half of what URDF says — a
        // box is half-extents, a cylinder / capsule is (radius,
        // half-length), a sphere is its radius.
        let mut b = every_joint_kind();
        let tip = *b
            .robot
            .links
            .iter()
            .find(|(_, l)| l.name == "tip")
            .unwrap()
            .0;
        let pose = Pose::from_translation(DVec3::Z * 0.01);
        b.robot.links.get_mut(&tip).unwrap().collision =
            riggen_core::CollisionPolicy::Primitives(vec![
                Primitive::Cylinder {
                    pose,
                    radius: 0.02,
                    length: 0.5,
                },
                Primitive::Sphere { pose, radius: 0.03 },
                Primitive::Capsule {
                    pose,
                    radius: 0.04,
                    length: 0.6,
                },
            ]);
        let xml = write(&b.resolve().unwrap(), &ExportOptions::default());
        for line in [
            "<geom class=\"collision\" type=\"box\" size=\"0.05 0.1 0.15\" pos=\"0 0 0.01\"/>",
            "<geom class=\"collision\" type=\"cylinder\" size=\"0.02 0.25\" pos=\"0 0 0.01\"/>",
            "<geom class=\"collision\" type=\"sphere\" size=\"0.03\" pos=\"0 0 0.01\"/>",
            "<geom class=\"collision\" type=\"capsule\" size=\"0.04 0.3\" pos=\"0 0 0.01\"/>",
        ] {
            assert!(xml.contains(line), "missing {line}\n{xml}");
        }
    }

    #[test]
    fn a_name_needing_escaping_is_escaped() {
        let mut b = every_joint_kind();
        b.robot.name = "a<b>&\"c\"".into();
        let xml = write(&b.resolve().unwrap(), &ExportOptions::default());
        assert!(
            xml.contains("<mujoco model=\"a&lt;b&gt;&amp;&quot;c&quot;\">"),
            "{xml}"
        );
    }
}
