//! The MJCF writer (docs/02-data-model.md §Format mapping, ADR-0004,
//! ADR-0008): nested `<body>`s in the resolved order, one `<joint>` per
//! movable edge inside the child body, `<inertial pos mass fullinertia>`
//! so MuJoCo does the principal-axes decomposition itself, meshes by stem
//! under `meshdir="meshes"`.

use riggen_core::glam::DVec3;
use riggen_core::{ActuatorSpec, JointKind, Pose, Primitive};

use crate::resolve::{ExportOptions, ResolvedActuator, ResolvedGeom, ResolvedJoint, ResolvedRobot};
use crate::xml::{Xml, num, quat, vec3};

/// The translucent orange of the unirobot example's collision class.
pub const COLLISION_RGBA: &str = "0.9 0.4 0.1 0.25";

pub fn write(robot: &ResolvedRobot, _options: &ExportOptions) -> String {
    let mut x = Xml::new();
    x.open("mujoco", &[("model", robot.name.clone())]);
    x.comment("Generated by riggen. Meshes are in meters (ADR-0008).");
    x.empty(
        "compiler",
        &[
            ("angle", "radian".into()),
            ("meshdir", "meshes".into()),
            ("autolimits", "true".into()),
        ],
    );

    x.open("default", &[]);
    x.open("default", &[("class", "visual".into())]);
    x.empty(
        "geom",
        &[
            ("type", "mesh".into()),
            ("contype", "0".into()),
            ("conaffinity", "0".into()),
            ("group", "2".into()),
        ],
    );
    x.close("default");
    x.open("default", &[("class", "collision".into())]);
    x.empty(
        "geom",
        &[("group", "3".into()), ("rgba", COLLISION_RGBA.into())],
    );
    x.close("default");
    x.close("default");

    if !robot.meshes.is_empty() {
        x.open("asset", &[]);
        for name in robot.meshes.keys() {
            x.empty(
                "mesh",
                &[("name", name.clone()), ("file", format!("{name}.stl"))],
            );
        }
        x.close("asset");
    }

    x.open("worldbody", &[]);
    if !robot.links.is_empty() {
        write_body(&mut x, robot, 0);
    }
    x.close("worldbody");

    // MJCF has no `<mimic>`: a coupled DoF is a solver equality, and
    // `polycoef` is `y - y0 = a0 + a1(x - x0) + …` over the two joints'
    // deviations from `qpos0`. We never write `ref`, so both references
    // are zero and `(offset, multiplier, 0, 0, 0)` is exactly URDF's rule
    // (ADR-0013). It is a *soft* constraint, not a reduction.
    if robot.joints.iter().any(|j| j.mimic.is_some()) {
        x.open("equality", &[]);
        for j in &robot.joints {
            let Some(m) = &j.mimic else { continue };
            x.empty(
                "joint",
                &[
                    ("joint1", j.name.clone()),
                    ("joint2", robot.joints[m.joint].name.clone()),
                    (
                        "polycoef",
                        format!("{} {} 0 0 0", num(m.offset), num(m.multiplier)),
                    ),
                ],
            );
        }
        x.close("equality");
    }

    // One element per actuator, under its own name (ADR-0023): MJCF
    // namespaces are per element type, so `model.actuator("shoulder")` and
    // `model.joint("shoulder")` coexist — and the default name is the
    // joint's, so `data.ctrl` stays indexable by the name the user already
    // knows unless a file said otherwise.
    if !robot.actuators.is_empty() {
        x.open("actuator", &[]);
        for a in &robot.actuators {
            write_actuator(&mut x, a, &robot.joints[a.joint]);
        }
        x.close("actuator");
    }

    x.close("mujoco");
    x.finish()
}

fn write_body(x: &mut Xml, robot: &ResolvedRobot, index: usize) {
    let link = &robot.links[index];
    let joint = robot.parent_joint(index);
    let mut attrs = vec![("name", link.name.clone())];
    if let Some(j) = joint {
        attrs.extend(pose_attrs(&j.origin));
    }
    x.open("body", &attrs);

    if index == 0 && robot.floating_base {
        x.empty("freejoint", &[("name", "root".into())]);
    }
    if let Some(j) = joint.filter(|j| j.kind.is_movable()) {
        // `joints[index - 1]` is `links[index]`'s parent joint.
        let driven = robot.actuators_on(index - 1).next().is_some();
        write_joint(x, j, driven);
    }
    if let Some(i) = &link.inertial {
        let m = &i.inertia;
        x.empty(
            "inertial",
            &[
                ("pos", vec3(i.com)),
                ("mass", num(i.mass)),
                (
                    "fullinertia",
                    // MuJoCo's order: Ixx Iyy Izz Ixy Ixz Iyz.
                    format!(
                        "{} {} {} {} {} {}",
                        num(m.x_axis.x),
                        num(m.y_axis.y),
                        num(m.z_axis.z),
                        num(m.y_axis.x),
                        num(m.z_axis.x),
                        num(m.z_axis.y)
                    ),
                ),
            ],
        );
    }
    for geom in &link.visuals {
        write_geom(x, "visual", geom);
    }
    for geom in &link.collisions {
        write_geom(x, "collision", geom);
    }
    // A frame is a bare `<site>` at the class defaults (ADR-0012): no
    // `size`, no `group`, so MuJoCo's own 0.005 m sphere renders it as a
    // visible marker and an override is a `<default>` the user adds.
    for site in &link.sites {
        let mut attrs = vec![("name", site.name.clone())];
        attrs.extend(pose_attrs(&site.pose));
        x.empty("site", &attrs);
    }
    for child in robot.child_joints(index) {
        write_body(x, robot, child.child);
    }
    x.close("body");
}

fn write_joint(x: &mut Xml, j: &ResolvedJoint, driven: bool) {
    let mut attrs = vec![
        ("name", j.name.clone()),
        (
            "type",
            match j.kind {
                JointKind::Prismatic => "slide",
                _ => "hinge",
            }
            .into(),
        ),
        ("axis", vec3(j.axis)),
    ];
    if let Some(l) = &j.limits {
        attrs.push(("range", format!("{} {}", num(l.lower), num(l.upper))));
    }
    let d = &j.dynamics;
    if d.damping != 0.0 {
        attrs.push(("damping", num(d.damping)));
    }
    if d.friction != 0.0 {
        attrs.push(("frictionloss", num(d.friction)));
    }
    if d.armature != 0.0 {
        attrs.push(("armature", num(d.armature)));
    }
    x.empty("joint", &attrs);
    // ADR-0004 §4, as amended by ADR-0014 and re-keyed by ADR-0023: what
    // MJCF cannot hold without an actuator is named, not dropped — but only
    // while **no** actuator targets the joint, or the apology would be a
    // lie beside the `<actuator>` a few lines down.
    if let Some(l) = j.limits.filter(|_| !driven) {
        x.comment(&format!(
            "joint {}: effort {} velocity {} need an <actuator>; not written",
            j.name,
            num(l.effort),
            num(l.velocity)
        ));
    }
}

/// One `<position>` / `<velocity>` / `<motor>` / `<general>`: `a` under
/// its own name, driving `j` (ADR-0014, ADR-0023, ADR-0024).
///
/// A `<general>` writes its three type names, its `prm` vectors with the
/// zeros MuJoCo would fill in trimmed off the end — `gainprm="200"`, not
/// ten numbers — and its `gear`, the way a `<motor>` does. It has no
/// preset to derive a `ctrlrange` from, so only what the file said is
/// written; MuJoCo's default is unlimited.
///
/// The ranges are **the actuator's own, else the joint's** (ADR-0024).
/// What the file said — `ResolvedActuator::ranges` — is written as it was
/// said, its `ctrllimited` / `forcelimited` explicit whenever the flag is
/// `Some`; only where it said nothing is a range derived: `ctrlrange` is
/// the joint's own range for a position servo and `±velocity` for a
/// velocity one — both out of `Limits`, so a `Continuous` joint has none —
/// while a motor's `ctrl` is the normalised `-1 1` that `gear` scales, and
/// `forcerange` is `±effort`. A zero `effort` or `velocity` is the
/// *unfilled* value, not a clamp to zero, so its attribute is left out and
/// MuJoCo's own unbounded default stands (`autolimits="true"` then leaves
/// the matching `*limited` off). A flag of `Some(false)` beside no range
/// derives nothing either: the file meant unlimited, and the joint's
/// numbers would clamp what it left open.
fn write_actuator(x: &mut Xml, a: &ResolvedActuator, j: &ResolvedJoint) {
    let pair = |[lo, hi]: [f64; 2]| format!("{} {}", num(lo), num(hi));
    let symmetric = |v: f64| (v != 0.0).then(|| pair([-v, v]));
    let (tag, gains, derived_ctrl) = match &a.spec {
        ActuatorSpec::Position { kp, kv } => (
            "position",
            vec![("kp", num(*kp)), ("kv", num(*kv))],
            j.limits.map(|l| pair([l.lower, l.upper])),
        ),
        ActuatorSpec::Velocity { kv } => (
            "velocity",
            vec![("kv", num(*kv))],
            j.limits.and_then(|l| symmetric(l.velocity)),
        ),
        ActuatorSpec::Motor { gear } => {
            ("motor", vec![("gear", num(*gear))], Some("-1 1".to_owned()))
        }
        ActuatorSpec::General(g) => {
            let mut attrs = vec![
                ("dyntype", g.dyntype.mjcf_name().to_owned()),
                ("gaintype", g.gaintype.mjcf_name().to_owned()),
                ("biastype", g.biastype.mjcf_name().to_owned()),
            ];
            attrs.extend(
                g.prms()
                    .into_iter()
                    .filter_map(|(name, prm)| Some((name, numbers(trimmed(prm))?))),
            );
            attrs.push(("gear", num(g.gear)));
            ("general", attrs, None)
        }
    };
    let derived_force = j.limits.and_then(|l| symmetric(l.effort));
    let own = &a.ranges;
    let range = |said: Option<[f64; 2]>, flag: Option<bool>, derived: Option<String>| {
        said.map(pair)
            .or_else(|| (flag != Some(false)).then_some(derived).flatten())
    };
    let mut attrs = vec![("name", a.name.clone()), ("joint", j.name.clone())];
    attrs.extend(gains);
    for (limited, range) in [
        (
            ("ctrllimited", own.ctrl_limited),
            ("ctrlrange", range(own.ctrl, own.ctrl_limited, derived_ctrl)),
        ),
        (
            ("forcelimited", own.force_limited),
            (
                "forcerange",
                range(own.force, own.force_limited, derived_force),
            ),
        ),
    ] {
        if let Some(flag) = limited.1 {
            attrs.push((limited.0, flag.to_string()));
        }
        if let Some(value) = range.1 {
            attrs.push((range.0, value));
        }
    }
    x.empty(tag, &attrs);
}

/// `prm` with the trailing zeros MuJoCo would fill in anyway left off —
/// but never emptied: `dynprm="0"` means zero where an absent `dynprm`
/// means MuJoCo's default of one.
fn trimmed(prm: &[f64]) -> &[f64] {
    let keep = prm.iter().rposition(|v| *v != 0.0).map_or(0, |i| i + 1);
    &prm[..keep.max(1).min(prm.len())]
}

/// A space-separated attribute value, or `None` for nothing to write.
fn numbers(values: &[f64]) -> Option<String> {
    (!values.is_empty()).then(|| values.iter().map(|v| num(*v)).collect::<Vec<_>>().join(" "))
}

fn write_geom(x: &mut Xml, class: &str, geom: &ResolvedGeom) {
    let mut attrs = vec![("class", class.to_owned())];
    match geom {
        ResolvedGeom::Mesh { name, pose, .. } => {
            if class == "collision" {
                attrs.push(("type", "mesh".into()));
            }
            attrs.push(("mesh", name.clone()));
            attrs.extend(pose_attrs(pose));
        }
        ResolvedGeom::Primitive(p) => {
            // MJCF `size` is half-extents for a box and (radius, half-length)
            // for a cylinder / capsule — the classic mistake, pinned in
            // `primitive_sizes_are_half_extents`.
            let (kind, size, pose) = match p {
                Primitive::Box { pose, size } => ("box", vec3(*size * 0.5), pose),
                Primitive::Cylinder {
                    pose,
                    radius,
                    length,
                } => (
                    "cylinder",
                    format!("{} {}", num(*radius), num(length * 0.5)),
                    pose,
                ),
                Primitive::Sphere { pose, radius } => ("sphere", num(*radius), pose),
                Primitive::Capsule {
                    pose,
                    radius,
                    length,
                } => (
                    "capsule",
                    format!("{} {}", num(*radius), num(length * 0.5)),
                    pose,
                ),
            };
            attrs.push(("type", kind.into()));
            attrs.push(("size", size));
            attrs.extend(pose_attrs(pose));
        }
    }
    x.empty("geom", &attrs);
}

/// `pos` and `quat`, each only when it is not the default.
fn pose_attrs(pose: &Pose) -> Vec<(&'static str, String)> {
    let mut attrs = Vec::new();
    if pose.t != DVec3::ZERO {
        attrs.push(("pos", vec3(pose.t)));
    }
    if quat(pose.r) != "1 0 0 0" {
        attrs.push(("quat", quat(pose.r)));
    }
    attrs
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::test_util::every_joint_kind;
    use riggen_core::{ActuatorRanges, BiasType, DynType, GainType, General, Limits};

    pub(crate) const GOLDEN: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<mujoco model="test">
  <!-- Generated by riggen. Meshes are in meters (ADR-0008). -->
  <compiler angle="radian" meshdir="meshes" autolimits="true"/>
  <default>
    <default class="visual">
      <geom type="mesh" contype="0" conaffinity="0" group="2"/>
    </default>
    <default class="collision">
      <geom group="3" rgba="0.9 0.4 0.1 0.25"/>
    </default>
  </default>
  <asset>
    <mesh name="cube" file="cube.stl"/>
  </asset>
  <worldbody>
    <body name="base_link">
      <inertial pos="0 0 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
      <geom class="visual" mesh="cube"/>
      <geom class="collision" type="mesh" mesh="cube"/>
      <site name="camera_mount" pos="0 0.03 0.04" quat="0.707106781187 0.707106781187 0 0"/>
      <body name="upper" pos="0 0 0.1">
        <joint name="upper_joint" type="hinge" axis="0 1 0" range="-1 1" damping="0.1"/>
        <inertial pos="0 0 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
        <geom class="visual" mesh="cube"/>
        <geom class="collision" type="mesh" mesh="cube"/>
        <body name="slider" pos="0 0 0.1">
          <joint name="slider_joint" type="slide" axis="0 0 1" range="-1 1"/>
          <!-- joint slider_joint: effort 1 velocity 1 need an <actuator>; not written -->
          <inertial pos="0 0 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
          <geom class="visual" mesh="cube"/>
          <geom class="collision" type="box" size="0.05 0.1 0.15" pos="0 0 0.01"/>
          <body name="wheel" pos="0 0 0.1">
            <joint name="wheel_joint" type="hinge" axis="0 0 1"/>
            <inertial pos="0 0.02 0" mass="2.7" fullinertia="0.0045 0.0045 0.0045 0 0 0"/>
            <geom class="visual" mesh="cube" pos="0 0.02 0" quat="0.707106781187 0.707106781187 0 0"/>
            <geom class="collision" type="mesh" mesh="cube" pos="0 0.02 0" quat="0.707106781187 0.707106781187 0 0"/>
            <body name="tip" pos="0 0 0.1">
              <site name="tcp" pos="0 0 0.05"/>
            </body>
          </body>
        </body>
      </body>
    </body>
  </worldbody>
  <equality>
    <joint joint1="slider_joint" joint2="upper_joint" polycoef="0.1 -0.5 0 0 0"/>
  </equality>
  <actuator>
    <position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrlrange="-1 1" forcerange="-1 1"/>
    <velocity name="wheel_joint" joint="wheel_joint" kv="2"/>
  </actuator>
</mujoco>
"#;

    #[test]
    fn golden_mjcf_for_every_joint_kind() {
        let b = every_joint_kind();
        let resolved = b.resolve().unwrap();
        let xml = write(&resolved, &ExportOptions::default());
        if xml != GOLDEN {
            for (i, (a, e)) in xml.lines().zip(GOLDEN.lines()).enumerate() {
                assert_eq!(a, e, "line {}", i + 1);
            }
            assert_eq!(xml.lines().count(), GOLDEN.lines().count());
        }
    }

    /// The element, the gains and the two ranges each preset writes — and
    /// the two zeros that mean "nobody filled this in" rather than "clamp
    /// it to zero" (ADR-0014). The golden above covers the third case, a
    /// `Continuous` joint, whose missing `Limits` leave both ranges out.
    #[test]
    fn each_preset_writes_its_element_with_ctrlrange_and_forcerange() {
        /// The `<actuator>` line for `upper_joint`, alone in the block.
        fn line(actuator: ActuatorSpec, effort: f64, velocity: f64) -> String {
            let mut b = every_joint_kind();
            // Only `upper_joint` is driven here, whatever `every_joint_kind`
            // set up: the line under test must be alone in the block.
            b.robot.actuators.clear();
            let mut driven = None;
            for (&id, j) in b.robot.joints.iter_mut() {
                let hinge = j.name == "upper_joint";
                if hinge {
                    driven = Some(id);
                    // Only the two ranges vary: moving `lower`/`upper`
                    // would move the slider's mimic reach with them.
                    j.limits = Some(Limits {
                        lower: -1.0,
                        upper: 1.0,
                        effort,
                        velocity,
                    });
                }
            }
            b.actuator(driven.expect("upper_joint is in the chain"), actuator);
            let xml = write(&b.resolve().unwrap(), &ExportOptions::default());
            assert!(
                !xml.contains("joint upper_joint: effort"),
                "an actuated joint keeps no apology (ADR-0004 §4 as amended)\n{xml}"
            );
            assert!(
                xml.contains("joint slider_joint: effort"),
                "one with no actuator still does\n{xml}"
            );
            xml.lines()
                .find(|l| l.contains(r#"joint="upper_joint""#))
                .unwrap_or_default()
                .trim()
                .to_owned()
        }

        assert_eq!(
            line(ActuatorSpec::Position { kp: 100.0, kv: 5.0 }, 2.0, 3.0),
            r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrlrange="-1 1" forcerange="-2 2"/>"#
        );
        // A velocity servo is commanded in the joint's own rate, so its
        // `ctrlrange` is the velocity limit, not the position one.
        assert_eq!(
            line(ActuatorSpec::Velocity { kv: 2.0 }, 2.0, 3.0),
            r#"<velocity name="upper_joint" joint="upper_joint" kv="2" ctrlrange="-3 3" forcerange="-2 2"/>"#
        );
        // A motor's `ctrl` is normalised; `gear` is what scales it.
        assert_eq!(
            line(ActuatorSpec::Motor { gear: 50.0 }, 2.0, 3.0),
            r#"<motor name="upper_joint" joint="upper_joint" gear="50" ctrlrange="-1 1" forcerange="-2 2"/>"#
        );
        // `effort` 0 is the unfilled value: no `forcerange`, so
        // `autolimits` leaves the force unbounded — MuJoCo's own default —
        // rather than clamping it to zero. Same for `velocity` 0.
        assert_eq!(
            line(ActuatorSpec::Position { kp: 100.0, kv: 5.0 }, 0.0, 3.0),
            r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrlrange="-1 1"/>"#
        );
        assert_eq!(
            line(ActuatorSpec::Velocity { kv: 2.0 }, 0.0, 0.0),
            r#"<velocity name="upper_joint" joint="upper_joint" kv="2"/>"#
        );
        // The escape hatch (ADR-0024): the three type names, each `prm`
        // vector trimmed of the zeros MuJoCo would fill in — but not
        // emptied — and `gear` like a motor's. No preset means no derived
        // `ctrlrange`; `forcerange` still follows the joint's effort.
        let general = |dynprm: Vec<f64>, gainprm: Vec<f64>, biasprm: Vec<f64>| {
            ActuatorSpec::General(General {
                dyntype: DynType::Filter,
                gaintype: GainType::Fixed,
                biastype: BiasType::Affine,
                dynprm,
                gainprm,
                biasprm,
                gear: 2.0,
            })
        };
        assert_eq!(
            line(
                general(
                    vec![0.1],
                    vec![200.0, 0.0, 0.0],
                    vec![0.0, -200.0, -5.0, 0.0]
                ),
                2.0,
                3.0
            ),
            r#"<general name="upper_joint" joint="upper_joint" dyntype="filter" gaintype="fixed" biastype="affine" dynprm="0.1" gainprm="200" biasprm="0 -200 -5" gear="2" forcerange="-2 2"/>"#
        );
        assert_eq!(
            line(general(vec![0.0, 0.0], Vec::new(), vec![0.0]), 0.0, 0.0),
            r#"<general name="upper_joint" joint="upper_joint" dyntype="filter" gaintype="fixed" biastype="affine" dynprm="0" biasprm="0" gear="2"/>"#,
            "an all-zero vector keeps one zero: absent would mean MuJoCo's default"
        );
        assert_eq!(
            line(ActuatorSpec::General(General::default()), 0.0, 0.0),
            r#"<general name="upper_joint" joint="upper_joint" dyntype="none" gaintype="fixed" biastype="none" gear="1"/>"#
        );
    }

    /// The ranges are the actuator's own, else the joint's (ADR-0024): what
    /// an imported file said comes back out as it was said, flags
    /// included, and only a riggen-authored actuator — every field `None`
    /// — has its ranges derived. `Some(false)` beside no range is the
    /// imported `<position>` that named no `ctrlrange`: unlimited, not
    /// clamped to the joint.
    #[test]
    fn an_actuators_own_ranges_win_over_the_joints_and_the_flags_are_explicit() {
        fn line(ranges: ActuatorRanges) -> String {
            let mut b = every_joint_kind();
            let driven = b.robot.joints.iter().find(|(_, j)| j.name == "upper_joint");
            let driven = *driven.expect("upper_joint is in the chain").0;
            b.robot.actuators.clear();
            let id = b.actuator(driven, ActuatorSpec::Position { kp: 100.0, kv: 5.0 });
            b.robot.actuators.get_mut(&id).unwrap().ranges = ranges;
            let xml = write(&b.resolve().unwrap(), &ExportOptions::default());
            xml.lines()
                .find(|l| l.contains("joint=\"upper_joint\""))
                .map(str::trim)
                .unwrap()
                .to_owned()
        }
        // Nothing said: the joint's range and effort, as always.
        assert_eq!(
            line(ActuatorRanges::default()),
            r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrlrange="-1 1" forcerange="-1 1"/>"#
        );
        // A narrower `ctrlrange` than the joint's, and a `forcerange` the
        // joint's effort does not agree with: the file's numbers stand.
        assert_eq!(
            line(ActuatorRanges {
                ctrl: Some([-0.5, 0.25]),
                force: Some([-30.0, 30.0]),
                ctrl_limited: None,
                force_limited: None,
            }),
            r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrlrange="-0.5 0.25" forcerange="-30 30"/>"#
        );
        // The file named no `ctrlrange` under `autolimits`: unlimited, so
        // the joint's range must not be invented for it. The effort still
        // derives, since nothing was said about force.
        assert_eq!(
            line(ActuatorRanges {
                ctrl_limited: Some(false),
                ..ActuatorRanges::default()
            }),
            r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrllimited="false" forcerange="-1 1"/>"#
        );
        // An explicit flag is written explicitly, beside its range — and
        // a `false` beside a range keeps the range, as MuJoCo does.
        assert_eq!(
            line(ActuatorRanges {
                ctrl: Some([-1.0, 1.0]),
                force: Some([-2.0, 2.0]),
                ctrl_limited: Some(true),
                force_limited: Some(false),
            }),
            r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrllimited="true" ctrlrange="-1 1" forcelimited="false" forcerange="-2 2"/>"#
        );
    }

    /// The two things `Joint::actuator` could not say (ADR-0023): an
    /// element under a name that is not its joint's, and two elements
    /// driving one joint. Both are what MJCF itself allows — namespaces are
    /// per element type, and MuJoCo sums the controls of every actuator on
    /// a joint — so both must come out of the writer as the document holds
    /// them.
    #[test]
    fn an_actuator_writes_its_own_name_and_a_joint_may_have_two() {
        let mut b = every_joint_kind();
        let wheel = *b
            .robot
            .joints
            .iter()
            .find(|(_, j)| j.name == "wheel_joint")
            .unwrap()
            .0;
        b.named_actuator("wheel_boost", wheel, ActuatorSpec::Motor { gear: 5.0 });
        let xml = write(&b.resolve().unwrap(), &ExportOptions::default());

        // By the trimmed line, not by `contains`: the apologetic comment
        // says "need an <actuator>" too.
        let block: Vec<&str> = xml
            .lines()
            .map(str::trim)
            .skip_while(|l| *l != "<actuator>")
            .skip(1)
            .take_while(|l| *l != "</actuator>")
            .collect();
        assert_eq!(
            block,
            [
                r#"<position name="upper_joint" joint="upper_joint" kp="100" kv="5" ctrlrange="-1 1" forcerange="-1 1"/>"#,
                r#"<velocity name="wheel_joint" joint="wheel_joint" kv="2"/>"#,
                r#"<motor name="wheel_boost" joint="wheel_joint" gear="5" ctrlrange="-1 1"/>"#,
            ],
            "in ActuatorId order, each under its own name\n{xml}"
        );
        // And the apology stays off a joint that any actuator drives — the
        // second one does not make it true again (ADR-0004 §4).
        assert!(!xml.contains("joint wheel_joint: effort"), "{xml}");
    }

    #[test]
    fn floating_base_adds_a_freejoint_under_the_root() {
        let b = every_joint_kind();
        let options = ExportOptions {
            floating_base: true,
            ..Default::default()
        };
        let resolved = crate::resolve(&b.robot, &b.store, &crate::ComputeNow, &options).unwrap();
        let xml = write(&resolved, &options);
        assert!(
            xml.contains("    <body name=\"base_link\">\n      <freejoint name=\"root\"/>\n"),
            "{xml}"
        );
    }

    #[test]
    fn primitive_sizes_are_half_extents() {
        // The classic mistake: MJCF `size` is half of what URDF says — a
        // box is half-extents, a cylinder / capsule is (radius,
        // half-length), a sphere is its radius.
        let mut b = every_joint_kind();
        let tip = *b
            .robot
            .links
            .iter()
            .find(|(_, l)| l.name == "tip")
            .unwrap()
            .0;
        let pose = Pose::from_translation(DVec3::Z * 0.01);
        b.robot.links.get_mut(&tip).unwrap().collision =
            riggen_core::CollisionPolicy::Primitives(vec![
                Primitive::Cylinder {
                    pose,
                    radius: 0.02,
                    length: 0.5,
                },
                Primitive::Sphere { pose, radius: 0.03 },
                Primitive::Capsule {
                    pose,
                    radius: 0.04,
                    length: 0.6,
                },
            ]);
        let xml = write(&b.resolve().unwrap(), &ExportOptions::default());
        for line in [
            "<geom class=\"collision\" type=\"box\" size=\"0.05 0.1 0.15\" pos=\"0 0 0.01\"/>",
            "<geom class=\"collision\" type=\"cylinder\" size=\"0.02 0.25\" pos=\"0 0 0.01\"/>",
            "<geom class=\"collision\" type=\"sphere\" size=\"0.03\" pos=\"0 0 0.01\"/>",
            "<geom class=\"collision\" type=\"capsule\" size=\"0.04 0.3\" pos=\"0 0 0.01\"/>",
        ] {
            assert!(xml.contains(line), "missing {line}\n{xml}");
        }
    }

    #[test]
    fn a_name_needing_escaping_is_escaped() {
        let mut b = every_joint_kind();
        b.robot.name = "a<b>&\"c\"".into();
        let xml = write(&b.resolve().unwrap(), &ExportOptions::default());
        assert!(
            xml.contains("<mujoco model=\"a&lt;b&gt;&amp;&quot;c&quot;\">"),
            "{xml}"
        );
    }
}
