//! The SDF writer (ADR-0016, docs/02-data-model.md §Format mapping): the
//! third dumb serialiser of one `ResolvedRobot`, and the one that has to
//! apologise least. SDF's own defaults are riggen's conventions — a
//! joint's pose is the child link frame (ADR-0004), an axis is expressed
//! in the joint frame — so a link's `<pose relative_to>` *is*
//! `ResolvedJoint::origin` and nothing is composed on the way out.

use std::path::Path;

use riggen_core::{ActuatorSpec, JointKind, Pose, Primitive};

use crate::resolve::{ExportOptions, MeshPathStyle, ResolvedGeom, ResolvedJoint, ResolvedRobot};
use crate::xml::{Xml, num, pose6, vec3};

/// The spec version we write. 1.11 is the first with `<axis><mimic>`, and
/// `libsdformat14` — what Gazebo Harmonic ships — reads it (ADR-0016 §1).
pub const VERSION: &str = "1.11";

/// `dir` is where the export lands: `MeshPathStyle::Absolute` names the
/// written mesh files by their absolute path.
pub fn write(robot: &ResolvedRobot, options: &ExportOptions, dir: &Path) -> String {
    let mut x = Xml::new();
    x.open("sdf", &[("version", VERSION.into())]);
    x.open("model", &[("name", robot.name.clone())]);
    x.comment("Generated by riggen. Meshes are in meters (ADR-0008).");
    for (i, link) in robot.links.iter().enumerate() {
        x.open("link", &[("name", link.name.clone())]);
        // The pose graph, spelled as the tree it came from: a link sits at
        // its parent joint's origin in its parent link's frame, and the
        // root sits at the model origin and says nothing.
        if let Some(joint) = robot.parent_joint(i) {
            x.text(
                "pose",
                &[("relative_to", robot.links[joint.parent].name.clone())],
                &pose6(&joint.origin),
            );
        }
        if let Some(inertial) = &link.inertial {
            let m = &inertial.inertia;
            x.open("inertial", &[]);
            // The CoM, in link axes: the tensor is about the CoM and
            // aligned with the link, so the pose carries no rotation.
            x.text("pose", &[], &pose6(&Pose::from_translation(inertial.com)));
            x.text("mass", &[], &num(inertial.mass));
            x.open("inertia", &[]);
            for (tag, value) in [
                ("ixx", m.x_axis.x),
                ("ixy", m.y_axis.x),
                ("ixz", m.z_axis.x),
                ("iyy", m.y_axis.y),
                ("iyz", m.z_axis.y),
                ("izz", m.z_axis.z),
            ] {
                x.text(tag, &[], &num(value));
            }
            x.close("inertia");
            x.close("inertial");
        }
        // SDF names every visual and collision, and the names have to be
        // unique inside the link, so they are the link's own plus the
        // index the resolver put them in.
        for (i, geom) in link.visuals.iter().enumerate() {
            write_geom(&mut x, "visual", &link.name, i, geom, options, dir);
        }
        for (i, geom) in link.collisions.iter().enumerate() {
            write_geom(&mut x, "collision", &link.name, i, geom, options, dir);
        }
        x.close("link");
    }
    // A fixed base is a fixed joint to SDF's reserved `world` frame; a
    // floating one is a model with nothing holding it, which is what MJCF
    // spells `<freejoint/>` (ADR-0016 §3).
    if !robot.floating_base
        && let Some(root) = robot.links.first()
    {
        x.open(
            "joint",
            &[("name", "world_joint".into()), ("type", "fixed".into())],
        );
        x.text("parent", &[], "world");
        x.text("child", &[], &root.name);
        x.close("joint");
    }
    for joint in &robot.joints {
        write_joint(&mut x, robot, joint);
    }
    // A named frame is SDF's own `<frame>` (ADR-0012's third spelling):
    // `<pose>`'s default `relative_to` is the `attached_to` frame, so the
    // pose goes out in the link frame verbatim.
    let sites = robot
        .links
        .iter()
        .flat_map(|l| l.sites.iter().map(move |s| (l, s)));
    for (link, site) in sites {
        x.open(
            "frame",
            &[
                ("name", site.name.clone()),
                ("attached_to", link.name.clone()),
            ],
        );
        x.text("pose", &[], &pose6(&site.pose));
        x.close("frame");
    }
    x.close("model");
    x.close("sdf");
    x.finish()
}

fn write_joint(x: &mut Xml, robot: &ResolvedRobot, j: &ResolvedJoint) {
    // All four kinds are SDF's own words, so none is approximated.
    let kind = match j.kind {
        JointKind::Fixed => "fixed",
        JointKind::Revolute => "revolute",
        JointKind::Continuous => "continuous",
        JointKind::Prismatic => "prismatic",
    };
    x.open("joint", &[("name", j.name.clone()), ("type", kind.into())]);
    x.text("parent", &[], &robot.links[j.parent].name);
    x.text("child", &[], &robot.links[j.child].name);
    // No `<pose>`: SDF already expresses a joint in the child link frame,
    // which is riggen's joint frame (ADR-0004), so the default is the
    // convention and writing it would be writing zeros (ADR-0016 §2).
    if j.kind.is_movable() {
        x.open("axis", &[]);
        // No `expressed_in` either: `<xyz>`'s default frame is the joint
        // frame, the same child link frame `ResolvedJoint::axis` is in.
        x.text("xyz", &[], &vec3(j.axis));
        if let Some(l) = &j.limits {
            x.open("limit", &[]);
            x.text("lower", &[], &num(l.lower));
            x.text("upper", &[], &num(l.upper));
            // A zero effort or velocity is the *unfilled* value (ADR-0014),
            // and SDF's default for both is infinity while a literal 0 is
            // a joint that can exert nothing — so it is omitted, as MJCF
            // omits `forcerange` and `ctrlrange`.
            if l.effort != 0.0 {
                x.text("effort", &[], &num(l.effort));
            }
            if l.velocity != 0.0 {
                x.text("velocity", &[], &num(l.velocity));
            }
            x.close("limit");
        }
        let d = &j.dynamics;
        if d.damping != 0.0 || d.friction != 0.0 {
            x.open("dynamics", &[]);
            x.text("damping", &[], &num(d.damping));
            x.text("friction", &[], &num(d.friction));
            x.close("dynamics");
        }
        // SDF 1.11's own coupled DoF, and the reason we write 1.11 at all
        // (ADR-0016 §1): `follower = multiplier·(leader − reference) +
        // offset` is ADR-0013's rule with `reference` at zero, and all
        // three numbers are written so the file states the whole thing.
        if let Some(m) = &j.mimic {
            x.open("mimic", &[("joint", robot.joints[m.joint].name.clone())]);
            x.text("multiplier", &[], &num(m.multiplier));
            x.text("offset", &[], &num(m.offset));
            x.text("reference", &[], &num(0.0));
            x.close("mimic");
        }
        x.close("axis");
    }
    if j.dynamics.armature != 0.0 {
        x.comment(&format!(
            "joint {}: armature {} is an MJCF property; not written",
            j.name,
            num(j.dynamics.armature)
        ));
    }
    // SDF has no actuator either. Gazebo drives a joint through a
    // `<plugin>` naming a C++ class, a shared library and a version of
    // Gazebo — a simulator configuration, not a robot description — so
    // ADR-0014's URDF reasoning applies word for word (ADR-0016 §5).
    if let Some(a) = j.actuator {
        let gains = match a {
            ActuatorSpec::Position { kp, kv } => format!("kp {} kv {}", num(kp), num(kv)),
            ActuatorSpec::Velocity { kv } => format!("kv {}", num(kv)),
            ActuatorSpec::Motor { gear } => format!("gear {}", num(gear)),
        };
        x.comment(&format!(
            "joint {}: a {} actuator ({gains}) is an MJCF property; not written",
            j.name,
            a.kind_name(),
        ));
    }
    x.close("joint");
}

fn write_geom(
    x: &mut Xml,
    tag: &str,
    link: &str,
    index: usize,
    geom: &ResolvedGeom,
    options: &ExportOptions,
    dir: &Path,
) {
    x.open(tag, &[("name", format!("{link}_{tag}_{index}"))]);
    match geom {
        ResolvedGeom::Mesh { name, pose, .. } => {
            x.text("pose", &[], &pose6(pose));
            x.open("geometry", &[]);
            x.open("mesh", &[]);
            x.text("uri", &[], &mesh_uri(name, options, dir));
            x.close("mesh");
            x.close("geometry");
        }
        // Every primitive riggen has, SDF has — including the capsule,
        // which URDF writes as a cylinder plus an apology (ADR-0016 §3).
        // SDF's capsule `<length>` is its cylindrical part, exactly ours.
        ResolvedGeom::Primitive(p) => {
            let (pose, shape, fields): (&Pose, &str, Vec<(&str, String)>) = match p {
                Primitive::Box { pose, size } => (pose, "box", vec![("size", vec3(*size))]),
                Primitive::Cylinder {
                    pose,
                    radius,
                    length,
                } => (
                    pose,
                    "cylinder",
                    vec![("radius", num(*radius)), ("length", num(*length))],
                ),
                Primitive::Sphere { pose, radius } => {
                    (pose, "sphere", vec![("radius", num(*radius))])
                }
                Primitive::Capsule {
                    pose,
                    radius,
                    length,
                } => (
                    pose,
                    "capsule",
                    vec![("radius", num(*radius)), ("length", num(*length))],
                ),
            };
            x.text("pose", &[], &pose6(pose));
            x.open("geometry", &[]);
            x.open(shape, &[]);
            for (field, value) in fields {
                x.text(field, &[], &value);
            }
            x.close(shape);
            x.close("geometry");
        }
    }
    x.close(tag);
}

/// The `<mesh><uri>` for `stem` under `options.mesh_paths` (ADR-0016 §4):
/// SDF's `model://` is URDF's `package://`, so the one dialog control
/// means one thing in both files.
pub fn mesh_uri(stem: &str, options: &ExportOptions, dir: &Path) -> String {
    let relative = format!("meshes/{stem}.stl");
    match &options.mesh_paths {
        MeshPathStyle::Relative => relative,
        MeshPathStyle::Package(package) => format!("model://{package}/{relative}"),
        MeshPathStyle::Absolute => {
            let path = dir.join(&relative);
            let path = riggen_core::absolute(&path).unwrap_or(path);
            format!("file://{}", path.display())
        }
    }
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::test_util::every_joint_kind;

    pub(crate) const GOLDEN: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<sdf version="1.11">
  <model name="test">
    <!-- Generated by riggen. Meshes are in meters (ADR-0008). -->
    <link name="base_link">
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
      <visual name="base_link_visual_0">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </visual>
      <collision name="base_link_collision_0">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </collision>
    </link>
    <link name="upper">
      <pose relative_to="base_link">0 0 0.1 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
      <visual name="upper_visual_0">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </visual>
      <collision name="upper_collision_0">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </collision>
    </link>
    <link name="slider">
      <pose relative_to="upper">0 0 0.1 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
      <visual name="slider_visual_0">
        <pose>0 0 0 0 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </visual>
      <collision name="slider_collision_0">
        <pose>0 0 0.01 0 0 0</pose>
        <geometry>
          <box>
            <size>0.1 0.2 0.3</size>
          </box>
        </geometry>
      </collision>
    </link>
    <link name="wheel">
      <pose relative_to="slider">0 0 0.1 0 0 0</pose>
      <inertial>
        <pose>0 0.02 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
      <visual name="wheel_visual_0">
        <pose>0 0.02 0 1.570796326795 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </visual>
      <collision name="wheel_collision_0">
        <pose>0 0.02 0 1.570796326795 0 0</pose>
        <geometry>
          <mesh>
            <uri>meshes/cube.stl</uri>
          </mesh>
        </geometry>
      </collision>
    </link>
    <link name="tip">
      <pose relative_to="wheel">0 0 0.1 0 0 0</pose>
    </link>
    <joint name="world_joint" type="fixed">
      <parent>world</parent>
      <child>base_link</child>
    </joint>
    <joint name="upper_joint" type="revolute">
      <parent>base_link</parent>
      <child>upper</child>
      <axis>
        <xyz>0 1 0</xyz>
        <limit>
          <lower>-1</lower>
          <upper>1</upper>
          <effort>1</effort>
          <velocity>1</velocity>
        </limit>
        <dynamics>
          <damping>0.1</damping>
          <friction>0</friction>
        </dynamics>
      </axis>
      <!-- joint upper_joint: a position actuator (kp 100 kv 5) is an MJCF property; not written -->
    </joint>
    <joint name="slider_joint" type="prismatic">
      <parent>upper</parent>
      <child>slider</child>
      <axis>
        <xyz>0 0 1</xyz>
        <limit>
          <lower>-1</lower>
          <upper>1</upper>
          <effort>1</effort>
          <velocity>1</velocity>
        </limit>
        <mimic joint="upper_joint">
          <multiplier>-0.5</multiplier>
          <offset>0.1</offset>
          <reference>0</reference>
        </mimic>
      </axis>
    </joint>
    <joint name="wheel_joint" type="continuous">
      <parent>slider</parent>
      <child>wheel</child>
      <axis>
        <xyz>0 0 1</xyz>
      </axis>
      <!-- joint wheel_joint: a velocity actuator (kv 2) is an MJCF property; not written -->
    </joint>
    <joint name="tip_joint" type="fixed">
      <parent>wheel</parent>
      <child>tip</child>
    </joint>
    <frame name="camera_mount" attached_to="base_link">
      <pose>0 0.03 0.04 1.570796326795 0 0</pose>
    </frame>
    <frame name="tcp" attached_to="tip">
      <pose>0 0 0.05 0 0 0</pose>
    </frame>
  </model>
</sdf>
"#;

    #[test]
    fn golden_sdf_for_every_joint_kind() {
        let b = every_joint_kind();
        let sdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        if sdf != GOLDEN {
            for (i, (a, e)) in sdf.lines().zip(GOLDEN.lines()).enumerate() {
                assert_eq!(a, e, "line {}", i + 1);
            }
            assert_eq!(sdf.lines().count(), GOLDEN.lines().count());
        }
        // Well-formed XML with the shape SDF wants, checked here so a
        // broken nesting fails in `cargo test` and not only in the CI job
        // that runs libsdformat over it (ADR-0016 §6).
        let root = crate::xml::parse(&sdf).unwrap();
        assert_eq!(root.tag, "sdf");
        assert_eq!(root.attr("version"), Some(VERSION));
        let model = root.child("model").unwrap();
        assert_eq!(model.attr("name"), Some("test"));
        assert_eq!(model.kids("link").count(), 5, "five links, flat");
        // The root says nothing about where it is; every other link names
        // its parent, and the chain is the tree (ADR-0016 §2).
        let links: Vec<_> = model.kids("link").collect();
        assert_eq!(links[0].child("pose"), None, "the root has no <pose>");
        for (link, parent) in links[1..]
            .iter()
            .zip(["base_link", "upper", "slider", "wheel"])
        {
            assert_eq!(
                link.child("pose").unwrap().attr("relative_to"),
                Some(parent),
                "{}",
                link.attr("name").unwrap()
            );
        }
        // An empty static link gets no `<inertial>`, as in URDF.
        assert_eq!(links[4].attr("name"), Some("tip"));
        assert_eq!(links[4].child("inertial"), None);
        // Every visual and collision is named, and uniquely inside its
        // link — SDF requires it, and a duplicate is an error there.
        for link in &links {
            let mut names: Vec<&str> = link
                .children
                .iter()
                .filter(|c| c.tag == "visual" || c.tag == "collision")
                .map(|c| c.attr("name").expect("named"))
                .collect();
            let count = names.len();
            names.sort_unstable();
            names.dedup();
            assert_eq!(names.len(), count, "{names:?}");
        }

        // The joints: the `world` weld first, then one per link in the
        // resolved order, none of them carrying a `<pose>` and no `<xyz>`
        // carrying an `expressed_in` — SDF's defaults are ADR-0004's
        // conventions and writing them would be writing zeros (ADR-0016 §2).
        let joints: Vec<_> = model.kids("joint").collect();
        let names: Vec<&str> = joints.iter().map(|j| j.attr("name").unwrap()).collect();
        assert_eq!(
            names,
            [
                "world_joint",
                "upper_joint",
                "slider_joint",
                "wheel_joint",
                "tip_joint"
            ]
        );
        for joint in &joints {
            assert_eq!(joint.child("pose"), None, "{}", joint.attr("name").unwrap());
            if let Some(axis) = joint.child("axis") {
                assert_eq!(axis.child("xyz").unwrap().attr("expressed_in"), None);
            }
        }
        // All four kinds by SDF's own names, so none is approximated.
        let kinds: Vec<&str> = joints.iter().map(|j| j.attr("type").unwrap()).collect();
        assert_eq!(
            kinds,
            ["fixed", "revolute", "prismatic", "continuous", "fixed"]
        );
        // A continuous joint has an axis and no `<limit>`: SDF's ±inf
        // default is what "unlimited" means, and `0 0` would be a locked
        // joint (ADR-0016 §3).
        let wheel = joints[3];
        assert!(wheel.child("axis").unwrap().child("limit").is_none());
        // The mimic is SDF 1.11's own element, not a comment (ADR-0016 §1).
        let mimic = joints[2]
            .child("axis")
            .unwrap()
            .child("mimic")
            .expect("the slider follows the hinge");
        assert_eq!(mimic.attr("joint"), Some("upper_joint"));
        assert_eq!(
            mimic
                .children
                .iter()
                .map(|c| c.tag.as_str())
                .collect::<Vec<_>>(),
            ["multiplier", "offset", "reference"]
        );
        // Two frames, each attached to its link (ADR-0012's third spelling).
        let frames: Vec<_> = model.kids("frame").collect();
        assert_eq!(
            frames
                .iter()
                .map(|f| (f.attr("name").unwrap(), f.attr("attached_to").unwrap()))
                .collect::<Vec<_>>(),
            [("camera_mount", "base_link"), ("tcp", "tip")]
        );
        // No dummy link and no fixed joint per frame, the way URDF needs
        // them: the five links and five joints above are all there are.
        assert_eq!(model.kids("link").count(), 5);
    }

    /// SDF has no actuator either, and Gazebo's `<plugin>` is a simulator
    /// configuration rather than a robot description, so ADR-0014's URDF
    /// answer stands word for word (ADR-0016 §5).
    #[test]
    fn an_actuator_is_a_comment_and_no_plugin_is_invented() {
        let mut b = every_joint_kind();
        for j in b.robot.joints.values_mut() {
            if j.name == "upper_joint" {
                j.actuator = Some(ActuatorSpec::Motor { gear: 50.0 });
            }
        }
        let sdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        assert!(
            sdf.contains(
                "<!-- joint upper_joint: a motor actuator (gear 50) is an MJCF property; not written -->"
            ),
            "{sdf}"
        );
        for invented in ["<plugin", "JointPositionController", "<gazebo"] {
            assert!(!sdf.contains(invented), "{invented} in\n{sdf}");
        }
        // The honest SDF answer is the `<limit>` it already writes.
        assert!(sdf.contains("<effort>1</effort>"), "{sdf}");
    }

    /// A zero effort or velocity is the *unfilled* value (ADR-0014), and
    /// SDF's default is infinity while a literal `0` is a joint that can
    /// exert nothing — so it is left out, as MJCF leaves out `forcerange`.
    #[test]
    fn an_unfilled_effort_or_velocity_is_omitted_not_written_as_zero() {
        let mut b = every_joint_kind();
        for j in b.robot.joints.values_mut() {
            if let Some(l) = j.limits.as_mut() {
                l.effort = 0.0;
                l.velocity = 3.0;
            }
        }
        let sdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        assert!(!sdf.contains("<effort>"), "{sdf}");
        assert!(sdf.contains("<velocity>3</velocity>"), "{sdf}");
        // The bounds themselves are still written, zero or not.
        assert!(sdf.contains("<lower>-1</lower>"), "{sdf}");
    }

    /// `floating_base` is what MJCF spells `<freejoint/>`: in SDF it is
    /// the absence of the weld to `world` (ADR-0016 §3).
    #[test]
    fn a_floating_base_is_the_world_joint_left_out() {
        let b = every_joint_kind();
        let fixed = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        assert!(fixed.contains("<parent>world</parent>"), "{fixed}");
        let options = ExportOptions {
            floating_base: true,
            ..Default::default()
        };
        let resolved = crate::resolve(&b.robot, &b.store, &crate::ComputeNow, &options).unwrap();
        let floating = write(&resolved, &options, Path::new("."));
        assert!(!floating.contains("world"), "{floating}");
        let root = crate::xml::parse(&floating).unwrap();
        let model = root.child("model").unwrap();
        assert_eq!(model.kids("joint").count(), 4, "the four real joints only");
    }

    /// The one place SDF beats URDF: a capsule stays a capsule, so the
    /// URDF writer's "written as a cylinder" apology has no counterpart
    /// here (ADR-0016 §3). `<box><size>` is full extents, as in URDF and
    /// unlike MJCF's half-extents.
    #[test]
    fn primitives_are_full_extents_and_a_capsule_stays_a_capsule() {
        let mut b = every_joint_kind();
        let tip = *b
            .robot
            .links
            .iter()
            .find(|(_, l)| l.name == "tip")
            .unwrap()
            .0;
        let pose = Pose::from_translation(riggen_core::glam::DVec3::Z * 0.01);
        b.robot.links.get_mut(&tip).unwrap().collision =
            riggen_core::CollisionPolicy::Primitives(vec![
                Primitive::Cylinder {
                    pose,
                    radius: 0.02,
                    length: 0.5,
                },
                Primitive::Sphere { pose, radius: 0.03 },
                Primitive::Capsule {
                    pose,
                    radius: 0.04,
                    length: 0.6,
                },
            ]);
        let sdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        for block in [
            "<box>\n            <size>0.1 0.2 0.3</size>\n          </box>",
            "<cylinder>\n            <radius>0.02</radius>\n            <length>0.5</length>\n          </cylinder>",
            "<sphere>\n            <radius>0.03</radius>\n          </sphere>",
            "<capsule>\n            <radius>0.04</radius>\n            <length>0.6</length>\n          </capsule>",
        ] {
            assert!(sdf.contains(block), "missing {block}\n{sdf}");
        }
        // No shape is apologised for. Every comment in the file is either
        // the generated-by line or an MJCF-only property (ADR-0016 §5) —
        // none of them is about geometry, which is the URDF writer's
        // "capsule written as a cylinder" having no counterpart here.
        for comment in sdf.lines().filter(|l| l.trim_start().starts_with("<!--")) {
            assert!(
                comment.contains("Generated by riggen") || comment.contains("is an MJCF property"),
                "{comment}"
            );
        }
        // …and the capsule did not become a second cylinder on the way out.
        assert_eq!(sdf.matches("<cylinder>").count(), 1, "{sdf}");
        assert_eq!(sdf.matches("<capsule>").count(), 1, "{sdf}");
        // The three of them are three named collisions on the one link.
        let root = crate::xml::parse(&sdf).unwrap();
        let tip = root
            .child("model")
            .unwrap()
            .kids("link")
            .find(|l| l.attr("name") == Some("tip"))
            .unwrap();
        let names: Vec<&str> = tip
            .kids("collision")
            .map(|c| c.attr("name").unwrap())
            .collect();
        assert_eq!(
            names,
            ["tip_collision_0", "tip_collision_1", "tip_collision_2"]
        );
    }

    /// `MeshPathStyle` needs no new variant for SDF: `model://` is what
    /// `package://` is to URDF, and an absolute path becomes a `file://`
    /// URI because `<uri>` is a URI (ADR-0016 §4).
    #[test]
    fn every_mesh_path_style() {
        let dir = Path::new("/exports/arm");
        let rel = ExportOptions::default();
        assert_eq!(mesh_uri("base", &rel, dir), "meshes/base.stl");
        let pkg = ExportOptions {
            mesh_paths: MeshPathStyle::Package("arm_description".into()),
            ..Default::default()
        };
        assert_eq!(
            mesh_uri("base", &pkg, dir),
            "model://arm_description/meshes/base.stl"
        );
        let abs = ExportOptions {
            mesh_paths: MeshPathStyle::Absolute,
            ..Default::default()
        };
        assert_eq!(
            mesh_uri("base", &abs, dir),
            "file:///exports/arm/meshes/base.stl"
        );
        // A relative export dir is made absolute against the cwd, and the
        // `file://` prefix leaves the leading slash of the path in place.
        let here = mesh_uri("base", &abs, Path::new("out"));
        assert!(here.starts_with("file:///"), "{here}");
        assert!(here.ends_with("/out/meshes/base.stl"), "{here}");
        // And the style reaches the written file, not just this helper.
        let b = every_joint_kind();
        let sdf = write(&b.resolve().unwrap(), &pkg, dir);
        assert!(
            sdf.contains("<uri>model://arm_description/meshes/cube.stl</uri>"),
            "{sdf}"
        );
    }
}
