//! The SDF writer (ADR-0016, docs/02-data-model.md §Format mapping): the
//! third dumb serialiser of one `ResolvedRobot`, and the one that has to
//! apologise least. SDF's own defaults are riggen's conventions — a
//! joint's pose is the child link frame (ADR-0004), an axis is expressed
//! in the joint frame — so a link's `<pose relative_to>` *is*
//! `ResolvedJoint::origin` and nothing is composed on the way out.

use std::path::Path;

use riggen_core::Pose;

use crate::resolve::{ExportOptions, ResolvedRobot};
use crate::xml::{Xml, num, pose6};

/// The spec version we write. 1.11 is the first with `<axis><mimic>`, and
/// `libsdformat14` — what Gazebo Harmonic ships — reads it (ADR-0016 §1).
pub const VERSION: &str = "1.11";

/// `dir` is where the export lands: `MeshPathStyle::Absolute` names the
/// written mesh files by their absolute path.
pub fn write(robot: &ResolvedRobot, _options: &ExportOptions, _dir: &Path) -> String {
    let mut x = Xml::new();
    x.open("sdf", &[("version", VERSION.into())]);
    x.open("model", &[("name", robot.name.clone())]);
    x.comment("Generated by riggen. Meshes are in meters (ADR-0008).");
    for (i, link) in robot.links.iter().enumerate() {
        x.open("link", &[("name", link.name.clone())]);
        // The pose graph, spelled as the tree it came from: a link sits at
        // its parent joint's origin in its parent link's frame, and the
        // root sits at the model origin and says nothing.
        if let Some(joint) = robot.parent_joint(i) {
            x.text(
                "pose",
                &[("relative_to", robot.links[joint.parent].name.clone())],
                &pose6(&joint.origin),
            );
        }
        if let Some(inertial) = &link.inertial {
            let m = &inertial.inertia;
            x.open("inertial", &[]);
            // The CoM, in link axes: the tensor is about the CoM and
            // aligned with the link, so the pose carries no rotation.
            x.text("pose", &[], &pose6(&Pose::from_translation(inertial.com)));
            x.text("mass", &[], &num(inertial.mass));
            x.open("inertia", &[]);
            for (tag, value) in [
                ("ixx", m.x_axis.x),
                ("ixy", m.y_axis.x),
                ("ixz", m.z_axis.x),
                ("iyy", m.y_axis.y),
                ("iyz", m.z_axis.y),
                ("izz", m.z_axis.z),
            ] {
                x.text(tag, &[], &num(value));
            }
            x.close("inertia");
            x.close("inertial");
        }
        x.close("link");
    }
    x.close("model");
    x.close("sdf");
    x.finish()
}

#[cfg(test)]
pub(crate) mod tests {
    use super::*;
    use crate::test_util::every_joint_kind;

    pub(crate) const GOLDEN: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<sdf version="1.11">
  <model name="test">
    <!-- Generated by riggen. Meshes are in meters (ADR-0008). -->
    <link name="base_link">
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
    </link>
    <link name="upper">
      <pose relative_to="base_link">0 0 0.1 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
    </link>
    <link name="slider">
      <pose relative_to="upper">0 0 0.1 0 0 0</pose>
      <inertial>
        <pose>0 0 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
    </link>
    <link name="wheel">
      <pose relative_to="slider">0 0 0.1 0 0 0</pose>
      <inertial>
        <pose>0 0.02 0 0 0 0</pose>
        <mass>2.7</mass>
        <inertia>
          <ixx>0.0045</ixx>
          <ixy>0</ixy>
          <ixz>0</ixz>
          <iyy>0.0045</iyy>
          <iyz>0</iyz>
          <izz>0.0045</izz>
        </inertia>
      </inertial>
    </link>
    <link name="tip">
      <pose relative_to="wheel">0 0 0.1 0 0 0</pose>
    </link>
  </model>
</sdf>
"#;

    #[test]
    fn golden_sdf_for_every_joint_kind() {
        let b = every_joint_kind();
        let sdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        if sdf != GOLDEN {
            for (i, (a, e)) in sdf.lines().zip(GOLDEN.lines()).enumerate() {
                assert_eq!(a, e, "line {}", i + 1);
            }
            assert_eq!(sdf.lines().count(), GOLDEN.lines().count());
        }
        // Well-formed XML with the shape SDF wants, checked here so a
        // broken nesting fails in `cargo test` and not only in the CI job
        // that runs libsdformat over it (ADR-0016 §6).
        let root = crate::xml::parse(&sdf).unwrap();
        assert_eq!(root.tag, "sdf");
        assert_eq!(root.attr("version"), Some(VERSION));
        let model = root.child("model").unwrap();
        assert_eq!(model.attr("name"), Some("test"));
        assert_eq!(model.kids("link").count(), 5, "five links, flat");
        // The root says nothing about where it is; every other link names
        // its parent, and the chain is the tree (ADR-0016 §2).
        let links: Vec<_> = model.kids("link").collect();
        assert_eq!(links[0].child("pose"), None, "the root has no <pose>");
        for (link, parent) in links[1..]
            .iter()
            .zip(["base_link", "upper", "slider", "wheel"])
        {
            assert_eq!(
                link.child("pose").unwrap().attr("relative_to"),
                Some(parent),
                "{}",
                link.attr("name").unwrap()
            );
        }
        // An empty static link gets no `<inertial>`, as in URDF.
        assert_eq!(links[4].attr("name"), Some("tip"));
        assert_eq!(links[4].child("inertial"), None);
    }
}
