//! The URDF writer (docs/02-data-model.md §Format mapping, ADR-0004): a
//! flat list of `<link>`s and `<joint>`s in the resolved order, `<origin
//! xyz rpy>` from `Pose::to_xyz_rpy`, `<inertia>` about the CoM in link
//! axes, `<mesh filename>` in the chosen [`MeshPathStyle`]. Verified by
//! the round-trip: `urdf-rs` parses this back and an independent FK from
//! the parsed numbers agrees with `riggen_core::fk`.

use std::path::Path;

use riggen_core::{JointKind, Pose, Primitive};

use crate::resolve::{ExportOptions, MeshPathStyle, ResolvedGeom, ResolvedJoint, ResolvedRobot};
use crate::xml::{Xml, num, vec3};

/// `dir` is where the export lands: `MeshPathStyle::Absolute` names the
/// written mesh files by their absolute path.
pub fn write(robot: &ResolvedRobot, options: &ExportOptions, dir: &Path) -> String {
    let mut x = Xml::new();
    x.open("robot", &[("name", robot.name.clone())]);
    x.comment("Generated by riggen. Meshes are in meters (ADR-0008).");
    for link in &robot.links {
        x.open("link", &[("name", link.name.clone())]);
        if let Some(i) = &link.inertial {
            let m = &i.inertia;
            x.open("inertial", &[]);
            x.empty("origin", &[("xyz", vec3(i.com)), ("rpy", "0 0 0".into())]);
            x.empty("mass", &[("value", num(i.mass))]);
            x.empty(
                "inertia",
                &[
                    ("ixx", num(m.x_axis.x)),
                    ("ixy", num(m.y_axis.x)),
                    ("ixz", num(m.z_axis.x)),
                    ("iyy", num(m.y_axis.y)),
                    ("iyz", num(m.z_axis.y)),
                    ("izz", num(m.z_axis.z)),
                ],
            );
            x.close("inertial");
        }
        for geom in &link.visuals {
            write_geom(&mut x, "visual", geom, options, dir);
        }
        for geom in &link.collisions {
            write_geom(&mut x, "collision", geom, options, dir);
        }
        x.close("link");
    }
    // URDF has no site, so a named frame is a massless childless link on a
    // fixed joint — the ROS convention `tf` and MoveIt read (ADR-0012).
    // Both blocks come after the real ones, so the file still reads
    // root-first.
    let sites = || {
        robot
            .links
            .iter()
            .flat_map(|l| l.sites.iter().map(move |s| (l, s)))
    };
    if sites().next().is_some() {
        x.comment("Named frames: one massless link on a fixed joint each (ADR-0012).");
    }
    for (_, site) in sites() {
        x.empty("link", &[("name", site.name.clone())]);
    }
    for joint in &robot.joints {
        write_joint(&mut x, robot, joint);
    }
    for (link, site) in sites() {
        x.open(
            "joint",
            &[
                ("name", format!("{}_fixed", site.name)),
                ("type", "fixed".into()),
            ],
        );
        x.empty("origin", &origin_attrs(&site.pose));
        x.empty("parent", &[("link", link.name.clone())]);
        x.empty("child", &[("link", site.name.clone())]);
        x.close("joint");
    }
    x.close("robot");
    x.finish()
}

fn write_joint(x: &mut Xml, robot: &ResolvedRobot, j: &ResolvedJoint) {
    let kind = match j.kind {
        JointKind::Fixed => "fixed",
        JointKind::Revolute => "revolute",
        JointKind::Continuous => "continuous",
        JointKind::Prismatic => "prismatic",
    };
    x.open("joint", &[("name", j.name.clone()), ("type", kind.into())]);
    x.empty("origin", &origin_attrs(&j.origin));
    x.empty("parent", &[("link", robot.links[j.parent].name.clone())]);
    x.empty("child", &[("link", robot.links[j.child].name.clone())]);
    if j.kind.is_movable() {
        x.empty("axis", &[("xyz", vec3(j.axis))]);
    }
    if let Some(l) = &j.limits {
        x.empty(
            "limit",
            &[
                ("lower", num(l.lower)),
                ("upper", num(l.upper)),
                ("effort", num(l.effort)),
                ("velocity", num(l.velocity)),
            ],
        );
    }
    let d = &j.dynamics;
    if d.damping != 0.0 || d.friction != 0.0 {
        x.empty(
            "dynamics",
            &[("damping", num(d.damping)), ("friction", num(d.friction))],
        );
    }
    // URDF's native spelling of a coupled DoF (ADR-0013). Both optional
    // attributes are written out rather than left to their defaults, so
    // the file says the whole rule.
    if let Some(m) = &j.mimic {
        x.empty(
            "mimic",
            &[
                ("joint", robot.joints[m.joint].name.clone()),
                ("multiplier", num(m.multiplier)),
                ("offset", num(m.offset)),
            ],
        );
    }
    if d.armature != 0.0 {
        x.comment(&format!(
            "joint {}: armature {} is an MJCF property; not written",
            j.name,
            num(d.armature)
        ));
    }
    x.close("joint");
}

fn write_geom(x: &mut Xml, tag: &str, geom: &ResolvedGeom, options: &ExportOptions, dir: &Path) {
    x.open(tag, &[]);
    match geom {
        ResolvedGeom::Mesh { name, pose, .. } => {
            x.empty("origin", &origin_attrs(pose));
            x.open("geometry", &[]);
            x.empty("mesh", &[("filename", mesh_filename(name, options, dir))]);
            x.close("geometry");
        }
        ResolvedGeom::Primitive(p) => {
            let (pose, tag, attrs): (&Pose, &str, Vec<(&str, String)>) = match p {
                Primitive::Box { pose, size } => (pose, "box", vec![("size", vec3(*size))]),
                Primitive::Cylinder {
                    pose,
                    radius,
                    length,
                } => (
                    pose,
                    "cylinder",
                    vec![("radius", num(*radius)), ("length", num(*length))],
                ),
                Primitive::Sphere { pose, radius } => {
                    (pose, "sphere", vec![("radius", num(*radius))])
                }
                Primitive::Capsule {
                    pose,
                    radius,
                    length,
                } => {
                    // URDF has no capsule: the cylinder of the same size,
                    // and a comment so nobody wonders where the caps went.
                    x.comment("capsule written as a cylinder: URDF has no capsule");
                    (
                        pose,
                        "cylinder",
                        vec![("radius", num(*radius)), ("length", num(*length))],
                    )
                }
            };
            x.empty("origin", &origin_attrs(pose));
            x.open("geometry", &[]);
            x.empty(tag, &attrs);
            x.close("geometry");
        }
    }
    x.close(tag);
}

/// The `<mesh filename>` for `stem` under `options.mesh_paths`.
pub fn mesh_filename(stem: &str, options: &ExportOptions, dir: &Path) -> String {
    let relative = format!("meshes/{stem}.stl");
    match &options.mesh_paths {
        MeshPathStyle::Relative => relative,
        MeshPathStyle::Package(package) => format!("package://{package}/{relative}"),
        MeshPathStyle::Absolute => {
            let path = dir.join(&relative);
            riggen_core::absolute(&path)
                .unwrap_or(path)
                .display()
                .to_string()
        }
    }
}

fn origin_attrs(pose: &Pose) -> Vec<(&'static str, String)> {
    let (xyz, rpy) = pose.to_xyz_rpy();
    vec![("xyz", vec3(xyz)), ("rpy", vec3(rpy))]
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::MeshStore;
    use crate::test_util::{every_joint_kind, fixtures};
    use riggen_core::glam::{DMat3, DMat4, DVec3};
    use riggen_core::{JointState, fk};
    use std::collections::BTreeMap;

    const GOLDEN: &str = r#"<?xml version="1.0" encoding="utf-8"?>
<robot name="test">
  <!-- Generated by riggen. Meshes are in meters (ADR-0008). -->
  <link name="base_link">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.7"/>
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.0045" iyz="0" izz="0.0045"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="upper">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.7"/>
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.0045" iyz="0" izz="0.0045"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="slider">
    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="2.7"/>
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.0045" iyz="0" izz="0.0045"/>
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0 0.01" rpy="0 0 0"/>
      <geometry>
        <box size="0.1 0.2 0.3"/>
      </geometry>
    </collision>
  </link>
  <link name="wheel">
    <inertial>
      <origin xyz="0 0.02 0" rpy="0 0 0"/>
      <mass value="2.7"/>
      <inertia ixx="0.0045" ixy="0" ixz="0" iyy="0.0045" iyz="0" izz="0.0045"/>
    </inertial>
    <visual>
      <origin xyz="0 0.02 0" rpy="1.570796326795 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </visual>
    <collision>
      <origin xyz="0 0.02 0" rpy="1.570796326795 0 0"/>
      <geometry>
        <mesh filename="meshes/cube.stl"/>
      </geometry>
    </collision>
  </link>
  <link name="tip">
  </link>
  <!-- Named frames: one massless link on a fixed joint each (ADR-0012). -->
  <link name="camera_mount"/>
  <link name="tcp"/>
  <joint name="upper_joint" type="revolute">
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <parent link="base_link"/>
    <child link="upper"/>
    <axis xyz="0 1 0"/>
    <limit lower="-1" upper="1" effort="1" velocity="1"/>
    <dynamics damping="0.1" friction="0"/>
  </joint>
  <joint name="slider_joint" type="prismatic">
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <parent link="upper"/>
    <child link="slider"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1" upper="1" effort="1" velocity="1"/>
    <mimic joint="upper_joint" multiplier="-0.5" offset="0.1"/>
  </joint>
  <joint name="wheel_joint" type="continuous">
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <parent link="slider"/>
    <child link="wheel"/>
    <axis xyz="0 0 1"/>
  </joint>
  <joint name="tip_joint" type="fixed">
    <origin xyz="0 0 0.1" rpy="0 0 0"/>
    <parent link="wheel"/>
    <child link="tip"/>
  </joint>
  <joint name="camera_mount_fixed" type="fixed">
    <origin xyz="0 0.03 0.04" rpy="1.570796326795 0 0"/>
    <parent link="base_link"/>
    <child link="camera_mount"/>
  </joint>
  <joint name="tcp_fixed" type="fixed">
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <parent link="tip"/>
    <child link="tcp"/>
  </joint>
</robot>
"#;

    #[test]
    fn golden_urdf_for_every_joint_kind() {
        let b = every_joint_kind();
        let urdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        if urdf != GOLDEN {
            for (i, (a, e)) in urdf.lines().zip(GOLDEN.lines()).enumerate() {
                assert_eq!(a, e, "line {}", i + 1);
            }
            assert_eq!(urdf.lines().count(), GOLDEN.lines().count());
        }
        // And urdf-rs reads it whole.
        let parsed = urdf_rs::read_from_string(&urdf).unwrap();
        // Five real links and joints, plus a dummy link and a fixed
        // joint for each of the two frames (ADR-0012).
        assert_eq!(parsed.links.len(), 7);
        assert_eq!(parsed.joints.len(), 6);
        assert_eq!(parsed.joints[0].joint_type, urdf_rs::JointType::Revolute);
        assert_eq!(parsed.joints[3].joint_type, urdf_rs::JointType::Fixed);
        // The `<mimic>` is URDF's own element, not a string we invented:
        // urdf-rs parses it back with the rule intact (ADR-0013).
        assert!(parsed.joints[0].mimic.is_none());
        let mimic = parsed.joints[1].mimic.as_ref().unwrap();
        assert_eq!(mimic.joint, "upper_joint");
        assert_eq!(mimic.multiplier, Some(-0.5));
        assert_eq!(mimic.offset, Some(0.1));
    }

    #[test]
    fn primitives_are_full_extents_and_a_capsule_becomes_a_cylinder() {
        let mut b = every_joint_kind();
        let tip = *b
            .robot
            .links
            .iter()
            .find(|(_, l)| l.name == "tip")
            .unwrap()
            .0;
        let pose = Pose::from_translation(DVec3::Z * 0.01);
        b.robot.links.get_mut(&tip).unwrap().collision =
            riggen_core::CollisionPolicy::Primitives(vec![
                Primitive::Cylinder {
                    pose,
                    radius: 0.02,
                    length: 0.5,
                },
                Primitive::Sphere { pose, radius: 0.03 },
                Primitive::Capsule {
                    pose,
                    radius: 0.04,
                    length: 0.6,
                },
            ]);
        let urdf = write(
            &b.resolve().unwrap(),
            &ExportOptions::default(),
            Path::new("."),
        );
        for line in [
            "<box size=\"0.1 0.2 0.3\"/>",
            "<cylinder radius=\"0.02\" length=\"0.5\"/>",
            "<sphere radius=\"0.03\"/>",
            "<!-- capsule written as a cylinder: URDF has no capsule -->",
            "<cylinder radius=\"0.04\" length=\"0.6\"/>",
        ] {
            assert!(urdf.contains(line), "missing {line}\n{urdf}");
        }
        assert!(!urdf.contains("<capsule"));
        // And urdf-rs reads every one of them.
        let parsed = urdf_rs::read_from_string(&urdf).unwrap();
        let tip = parsed.links.iter().find(|l| l.name == "tip").unwrap();
        assert_eq!(tip.collision.len(), 3);
    }

    #[test]
    fn every_mesh_path_style() {
        let dir = Path::new("/exports/arm");
        let rel = ExportOptions::default();
        assert_eq!(mesh_filename("base", &rel, dir), "meshes/base.stl");
        let pkg = ExportOptions {
            mesh_paths: MeshPathStyle::Package("arm_description".into()),
            ..Default::default()
        };
        assert_eq!(
            mesh_filename("base", &pkg, dir),
            "package://arm_description/meshes/base.stl"
        );
        let abs = ExportOptions {
            mesh_paths: MeshPathStyle::Absolute,
            ..Default::default()
        };
        assert_eq!(
            mesh_filename("base", &abs, dir),
            "/exports/arm/meshes/base.stl"
        );
        // A relative export dir is made absolute against the cwd.
        let here = mesh_filename("base", &abs, Path::new("out"));
        assert!(Path::new(&here).is_absolute(), "{here}");
        assert!(here.ends_with("/out/meshes/base.stl"), "{here}");
    }

    /// FK from the parsed URDF alone: `xyz rpy` and `axis` as urdf-rs hands
    /// them, glam matrices, no `Pose`, no `riggen_core::fk`. The URDF
    /// convention: `T_child = T_parent · Trans(xyz) · Rz(y)·Ry(p)·Rx(r) ·
    /// motion(axis, q)`.
    fn independent_fk(robot: &urdf_rs::Robot, q: &BTreeMap<&str, f64>) -> BTreeMap<String, DMat4> {
        let mut world: BTreeMap<String, DMat4> = BTreeMap::new();
        let parents: std::collections::BTreeSet<&str> = robot
            .joints
            .iter()
            .map(|j| j.parent.link.as_str())
            .collect();
        let children: std::collections::BTreeSet<&str> =
            robot.joints.iter().map(|j| j.child.link.as_str()).collect();
        let root = robot
            .links
            .iter()
            .map(|l| l.name.as_str())
            .find(|n| parents.contains(n) && !children.contains(n))
            .expect("one root");
        world.insert(root.to_owned(), DMat4::IDENTITY);
        // Joints are written parent-first, so one pass resolves them all.
        for j in &robot.joints {
            let parent = world[&j.parent.link];
            let [x, y, z] = *j.origin.xyz;
            let [r, p, yw] = *j.origin.rpy;
            let rot =
                DMat3::from_rotation_z(yw) * DMat3::from_rotation_y(p) * DMat3::from_rotation_x(r);
            let origin = DMat4::from_translation(DVec3::new(x, y, z)) * DMat4::from_mat3(rot);
            let axis = DVec3::from_array(*j.axis.xyz).normalize();
            let qj = q.get(j.name.as_str()).copied().unwrap_or(0.0);
            let motion = match j.joint_type {
                urdf_rs::JointType::Revolute | urdf_rs::JointType::Continuous => {
                    DMat4::from_axis_angle(axis, qj)
                }
                urdf_rs::JointType::Prismatic => DMat4::from_translation(axis * qj),
                _ => DMat4::IDENTITY,
            };
            world.insert(j.child.link.clone(), parent * origin * motion);
        }
        world
    }

    #[test]
    fn round_trip_fk_agrees_on_a_grid() {
        let (robot, _) = riggen_core::load(&fixtures().join("arm/arm.riggen")).unwrap();
        let (store, errors) = MeshStore::load(&robot);
        assert!(errors.is_empty(), "{errors:?}");
        let resolved = crate::resolve(
            &robot,
            &store,
            &crate::ComputeNow,
            &ExportOptions::default(),
        )
        .unwrap();
        let urdf = write(&resolved, &ExportOptions::default(), Path::new("."));
        let parsed = urdf_rs::read_from_string(&urdf).unwrap();

        let movable: Vec<_> = robot
            .joints
            .iter()
            .filter(|(_, j)| j.kind.is_movable())
            .collect();
        assert_eq!(movable.len(), 3);
        let fore = *robot
            .links
            .iter()
            .find(|(_, l)| l.name == "fore")
            .unwrap()
            .0;
        let grid = [-1.2, -0.4, 0.0, 0.7, 1.5];
        let mut compared = 0;
        for a in grid {
            for b in grid {
                for c in grid {
                    let values = [a, b, c];
                    let mut state = JointState::new();
                    for ((id, _), v) in movable.iter().zip(values) {
                        state.set(**id, v);
                    }
                    // `independent_fk` knows nothing about `<mimic>` — it
                    // is deliberately the dumbest possible reader — so it
                    // is handed the configuration the couplings produce.
                    // What the `<mimic>` element itself means is pinned by
                    // the golden and by MuJoCo, not here.
                    let state = riggen_core::resolve_q(&robot, &state);
                    let q: BTreeMap<&str, f64> = movable
                        .iter()
                        .map(|(id, joint)| (joint.name.as_str(), state.get(**id)))
                        .collect();
                    let ours = fk(&robot, &state)[&fore].to_mat4();
                    let theirs = independent_fk(&parsed, &q)["fore"];
                    let diff = (ours - theirs).to_cols_array();
                    let worst = diff.iter().fold(0.0f64, |m, v| m.max(v.abs()));
                    assert!(worst < 1e-9, "q = {values:?}: {worst:e}\n{ours}\n{theirs}");
                    compared += 1;
                }
            }
        }
        assert_eq!(compared, 125);
    }
}
